In [25]:
import numpy
num_array = numpy.array([10 , 20 , 30 , 40], dtype = "int64")
#num_array = numpy.array([10 , 20 , 30 , 40, "City"], dtype = "int64")
print(num_array)
print(type(num_array))
print(num_array.dtype) #using dtype we are able to see data type of array collection

[10 20 30 40]
<class 'numpy.ndarray'>
int64


In [30]:
#num_array = numpy.array([10 , 20 , 30 , 40 , "Name"], dtype = "float64")
num_array = numpy.array([10 , 20 , 30 , 40 , "Name"], dtype = "U")
#dtype = U  (means string data type)
print(num_array)


['10' '20' '30' '40' 'Name']


In [15]:
numbers = [10, 20 ,30 ,40 , "NAme" , 3.5]
print(numbers)
print(type(numbers))

[10, 20, 30, 40, 'NAme', 3.5]
<class 'list'>


In [17]:
import numpy as np
array = np.array([1 ,2 ,3, 4 ,5 ,6 ,7 ,8])
print(array[0])
print(array[1])
print(array[2:])
print(array[3:7])
print(array.ndim)

1
2
[3 4 5 6 7 8]
[4 5 6 7]
1


In [18]:
a = np.array([[1 ,2 ,3 ], [11, 22 , 33], [111, 222 ,333 ]])
print(a.shape)
print(a[0][0])
print(a[0][1])
print(a[1][0])
print(a[2][0])
print(a[1][2])
a[0][0] = 99
print(a)
print(a.ndim)

(3, 3)
1
2
11
111
33
[[ 99   2   3]
 [ 11  22  33]
 [111 222 333]]
2


In [19]:
a = np.array([[[1 ,2 ,3 ], [11, 22 , 33], [111, 222 ,333 ]]])
print(a.ndim)

3


In [20]:
zero_value = np.zeros(3)
print(zero_value)

[0. 0. 0.]


In [21]:
one_value = np.ones(5)
print(one_value)

[1. 1. 1. 1. 1.]


In [23]:
range_array = np.arange(10)
print(range_array)

[0 1 2 3 4 5 6 7 8 9]


In [24]:
range_array = np.arange(5, 10)
print(range_array)

[5 6 7 8 9]


In [25]:
range_array = np.arange(0, 20, 2)
print(range_array)

[ 0  2  4  6  8 10 12 14 16 18]


In [26]:
range_array = np.arange(1, 20, 2)
print(range_array)

[ 1  3  5  7  9 11 13 15 17 19]


In [31]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print("Before Sort :" , arr)
print("After Sort :", np.sort(arr))
print(arr.size)

Before Sort : [2 1 5 3 7 4 6 8]
After Sort : [1 2 3 4 5 6 7 8]
8


In [39]:
random_value = np.random.randint(14 , 20, 10)
random_salary = np.random.randint(25000 , 50000, 6)
print(random_value)
print(random_salary)

[16 16 18 18 19 19 16 16 17 15]
[36660 39732 47556 30386 35126 46526]
